/**
 * This file was generated by the JPA Modeler
 */ 

package de.calendar.model;

import de.calendar.utils.CalendarUtils;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.validation.constraints.Size;

/**
 * Hier werden die Events gespeichert.
 * @author  KAABERT
 */

@Entity
public class Event implements Serializable {

    public static final DateTimeFormatter DATETIME_FORMAT = dateFormat("dd.MM.yyyy HH:mm");

    private static DateTimeFormatter dateFormat(String s) {
        return DateTimeFormatter.ofPattern(s).withLocale(Locale.GERMANY);
    }

    @Deprecated
    public Event() {
    }

    public Event(String title, String start, String end) {
        this.title = title;
        setStart(start);
        setEnd(end);

        this.owner = new ArrayList<>();
        this.subscribers = new ArrayList<>();
        this.invitations = new ArrayList<>();
    }

    public Event(String title, LocalDateTime start, LocalDateTime end, User owner) {
        this.title = title;
        setStart(start);
        setEnd(end);

        this.owner = new ArrayList<>();
        this.subscribers = new ArrayList<>();
        this.invitations = new ArrayList<>();

        this.owner.add(owner);
    }

    @Id

    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;

    @Basic
    private String start;

    @Basic
    private String end;

    @Basic
    @Size(min=3,max=56)
    private String title;

    @OneToMany(targetEntity = Invitation.class)
    private List<Invitation> invitations;

    @ManyToMany(targetEntity = User.class)
    private List<User> owner;

    @ManyToMany(targetEntity = User.class,mappedBy = "subscriptions")
    private List<User> subscribers;

    public Event(String title, LocalDateTime start, LocalDateTime end) {
        this.title = title;
        this.start = CalendarUtils.format(start);
        this.end = CalendarUtils.format(end);

        this.invitations = new ArrayList<>();
        this.owner = new ArrayList<>();
        this.subscribers = new ArrayList<>();
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStartString() {
        return this.start;
    }

    public LocalDateTime getStart()  {
        return CalendarUtils.parse(this.start);
    }
    
    public void setStart(String start) {
        this.start = CalendarUtils.format(CalendarUtils.parse(start));
    }

    public void setStart(LocalDateTime start) {
        this.start = CalendarUtils.format(start);
    }

    public String getEndString() {
        return this.end;
    }

    public LocalDateTime getEnd() {
        return CalendarUtils.parse(this.end);
    }

    public void setEnd(String end) {
        this.end = CalendarUtils.format(CalendarUtils.parse(end));
    }

    public void setEnd(LocalDateTime end) {
        this.end = CalendarUtils.format(end);
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public List<Invitation> getInvitations() {
        return this.invitations;
    }

    public void setInvitations(List<Invitation> invitations) {
        this.invitations = invitations;
    }

    public List<User> getOwner() {
        return this.owner;
    }

    public void setOwner(List<User> owner) {
        this.owner = owner;
    }

    public List<User> getSubscribers() {
        return this.subscribers;
    }

    public void setSubscribers(List<User> subscribers) {
        this.subscribers = subscribers;
    }

    @Override
    public String toString() {
        return "Event{" + " id=" + id + ", start=" + start + ", end=" + end + ", title=" + title + ", owner=" + owner + ", subscribers=" + subscribers + '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Event event = (Event) o;

        if (!start.equals(event.start)) return false;
        if (!end.equals(event.end)) return false;
        if (!title.equals(event.title)) return false;
        return invitations.equals(event.invitations);
    }

    @Override
    public int hashCode() {
        int result = start.hashCode();
        result = 31 * result + end.hashCode();
        result = 31 * result + title.hashCode();
        result = 31 * result + invitations.hashCode();
        return result;
    }
}
